// 336 JLPT N3 Kanji with On/Kun readings, Indonesian meanings, and Jukugo compounds

const rawKanjiData = [
  // 1-20 (Politik, Hukum, Masyarakat)
  { k: "政", on: "セイ、ショウ", kun: "まつりごと", m: "Pemerintahan, politik", s: 9, w: [["政治", "せいじ", "Politik"], ["政府", "せいふ", "Pemerintah"]] },
  { k: "治", on: "ジ、チ", kun: "おさ・める、なお・る", m: "Memerintah, sembuh, merawat", s: 8, w: [["治る", "なおる", "Sembuh"], ["治安", "ちあん", "Ketertiban umum"]] },
  { k: "経", on: "ケイ、キョウ", kun: "へ・る", m: "Melewati, mengelola", s: 11, w: [["経済", "けいざい", "Ekonomi"], ["経験", "けいけん", "Pengalaman"]] },
  { k: "済", on: "サイ、ザイ", kun: "す・む、す・ます", m: "Selesai, lunas", s: 11, w: [["済む", "すむ", "Selesai"], ["返済", "へんさい", "Pelunasan cicilan"]] },
  { k: "歴", on: "レキ", kun: "", m: "Riwayat, sejarah", s: 14, w: [["歴史", "れきし", "Sejarah"], ["履歴書", "りれきしょ", "CV / riwayat hidup"]] },
  { k: "史", on: "シ", kun: "", m: "Catatan sejarah", s: 5, w: [["日本史", "にほんし", "Sejarah Jepang"], ["世界史", "せかいし", "Sejarah dunia"]] },
  { k: "育", on: "イク", kun: "そだ・つ、そだ・てる", m: "Mendidik, tumbuh", s: 8, w: [["教育", "きょういく", "Pendidikan"], ["育てる", "そだてる", "Membesarkan"]] },
  { k: "化", on: "カ、ケ", kun: "ば・ける", m: "Berubah, transformasi", s: 4, w: [["文化", "ぶんか", "Kebudayaan"], ["化学", "かがく", "Kimia"]] },
  { k: "理", on: "リ", kun: "ことわり", m: "Nalar, alasan, hukum alam", s: 11, w: [["理由", "りゆう", "Alasan"], ["料理", "りょうり", "Masakan"]] },
  { k: "科", on: "カ", kun: "", m: "Departemen, jurusan ilmu", s: 9, w: [["科学", "かがく", "Sains"], ["教科書", "きょうかしょ", "Buku teks pelajaran"]] },
  { k: "数", on: "スウ、ス", kun: "かず、かぞ・える", m: "Jumlah, angka, berhitung", s: 13, w: [["数字", "すうじ", "Angka"], ["数学", "すうがく", "Matematika"]] },
  { k: "図", on: "ズ、ト", kun: "はか・る", m: "Gambar, peta, merencanakan", s: 7, w: [["地図", "ちず", "Peta"], ["図書館", "としょかん", "Perpustakaan"]] },
  { k: "館", on: "カン", kun: "やかた", m: "Gedung, balai besar", s: 16, w: [["博物館", "はくぶつかん", "Museum"], ["映画館", "えいがかん", "Bioskop"]] },
  { k: "線", on: "セン", kun: "すじ", m: "Garis, jalur lintasan", s: 15, w: [["新幹線", "しんかんせん", "Shinkansen"], ["地下鉄線", "ちかてつせん", "Jalur subway"]] },
  { k: "面", on: "メン", kun: "おも、おもて、つら", m: "Permukaan, wajah, sisi", s: 9, w: [["面接", "めんせつ", "Wawancara kerja"], ["方面", "ほうめん", "Arah/jurusan"]] },
  { k: "発", on: "ハツ、ホツ", kun: "た・つ", m: "Berangkat, memancarkan, terbit", s: 9, w: [["発表", "はっぴょう", "Presentasi"], ["出発", "しゅっぱつ", "Keberangkatan"]] },
  { k: "表", on: "ヒョウ", kun: "おもて、あらわ・す", m: "Tabel, bagian luar, menyatakan", s: 8, w: [["表現", "ひょうげん", "Ungkapan"], ["代表", "だいひょう", "Perwakilan"]] },
  { k: "現", on: "ゲン", kun: "あらわ・れる", m: "Muncul, nyata, sekarang", s: 11, w: [["現在", "げんざい", "Saat ini"], ["現象", "げんしょう", "Fenomena"]] },
  { k: "調", on: "チョウ", kun: "しら・べる、ととの・う", m: "Menyelidiki, nada, harmoni", s: 15, w: [["調査", "ちょうさ", "Investigasi/riset"], ["調子", "ちょうし", "Kondisi tubuh/alat"]] },
  { k: "査", on: "サ", kun: "", m: "Memeriksa, meninjau", s: 9, w: [["検査", "けんさ", "Pemeriksaan medis"], ["審査", "しんさ", "Penilaian/penjurian"]] },

  // 21-40
  { k: "法", on: "ホウ、ハッ", kun: "", m: "Hukum, metode, kaidah", s: 8, w: [["法律", "ほうりつ", "Hukum"], ["方法", "ほうほう", "Metode / cara"]] },
  { k: "規", on: "キ", kun: "", m: "Standar, aturan", s: 11, w: [["規則", "きそく", "Peraturan"], ["定規", "じょうぎ", "Penggaris"]] },
  { k: "則", on: "ソク", kun: "のっと・る", m: "Kaidah, asas", s: 9, w: [["原則", "げんそく", "Prinsip dasar"], ["反則", "はんそく", "Pelanggaran"]] },
  { k: "制", on: "セイ", kun: "", m: "Sistem, kendali, batas", s: 8, w: [["制度", "せいど", "Sistem / tatanan"], ["制限", "せいげん", "Pembatasan"]] },
  { k: "度", on: "ド、ト", kun: "たび", m: "Derajat, kali, batasan", s: 9, w: [["態度", "たいど", "Sikap"], ["温度", "おんど", "Temperatur"]] },
  { k: "役", on: "ヤク、エキ", kun: "", m: "Peran, tugas, dinas", s: 7, w: [["役に立つ", "やくにたつ", "Bermanfaat"], ["役員", "やくいん", "Pejabat eksekutif"]] },
  { k: "判", on: "ハン、バン", kun: "わか・る", m: "Menilai, stempel, vonis", s: 7, w: [["判断", "はんだん", "Keputusan/penilaian"], ["裁判", "さいばん", "Pengadilan"]] },
  { k: "断", on: "ダン", kun: "ことわ・る、た・つ", m: "Memutus, menolak, tegas", s: 11, w: [["断る", "ことわる", "Menolak"], ["決断", "けつだん", "Ketegasan tekad"]] },
  { k: "告", on: "コク", kun: "つ・げる", m: "Memberitahu, membeberkan", s: 7, w: [["広告", "こうこく", "Iklan"], ["報告", "ほうこく", "Laporan"]] },
  { k: "報", on: "ホウ", kun: "むく・いる", m: "Berita, balasan", s: 12, w: [["情報", "じょうほう", "Informasi"], ["予報", "よほう", "Prakiraan cuaca"]] },
  { k: "連", on: "レン", kun: "つ・れる、つら・なる", m: "Menghubungkan, memimpin", s: 10, w: [["連絡", "れんらく", "Komunikasi"], ["連休", "れんきゅう", "Libur beruntun"]] },
  { k: "絡", on: "ラク", kun: "から・む", m: "Terjerat, terhubung", s: 12, w: [["連絡先", "れんらくさき", "Kontak person"], ["短絡", "たんらく", "Gegabah / korsleting"]] },
  { k: "信", on: "シン", kun: "しん・じる", m: "Percaya, pesan", s: 9, w: [["信用", "しんよう", "Kepercayaan"], ["自信", "じしん", "Percaya diri"]] },
  { k: "号", on: "ゴウ", kun: "", m: "Nomor, tanda, nama sebutan", s: 5, w: [["信号", "しんごう", "Lampu lalu lintas"], ["番号", "ばんごう", "Nomor urut"]] },
  { k: "機", on: "キ", kun: "はた", m: "Mesin, kesempatan, pesawat", s: 16, w: [["機会", "きかい", "Kesempatan"], ["飛行機", "ひこうき", "Pesawat terbang"]] },
  { k: "械", on: "カイ", kun: "", m: "Perangkat, perkakas mesin", s: 11, w: [["機械", "きかい", "Mesin"], ["器械", "きかい", "Instrumen aparatur"]] },
  { k: "関", on: "カン", kun: "せき、かか・わる", m: "Kaitan, pos gerbang", s: 14, w: [["関係", "かんけい", "Hubungan"], ["関心", "かんしん", "Minat/perhatian"]] },
  { k: "係", on: "ケイ", kun: "かか・る、かかり", m: "Petugas penanggung jawab, relasi", s: 9, w: [["係員", "かかりいん", "Petugas staf"], ["関係者", "かんけいしゃ", "Pihak terkait"]] },
  { k: "設", on: "セツ", kun: "もう・ける", m: "Mendirikan, memasang", s: 11, w: [["設計", "せっけい", "Perancangan/desain"], ["施設", "しせつ", "Fasilitas"]] },
  { k: "備", on: "ビ", kun: "そな・える、そな・わる", m: "Mempersiapkan, melengkapi", s: 12, w: [["準備", "じゅんび", "Persiapan"], ["予備", "よび", "Cadangan"]] },

  // 41-60
  { k: "客", on: "キャク、カク", kun: "", m: "Tamu, pelanggan", s: 9, w: [["客席", "きゃくせき", "Tempat duduk tamu"], ["乗客", "じょうきゃく", "Penumpang"]] },
  { k: "席", on: "セキ", kun: "むしろ", m: "Kursi, bangku", s: 10, w: [["出席", "しゅっせき", "Kehadiran"], ["指定席", "していせき", "Kursi bernomor"]] },
  { k: "常", on: "ジョウ", kun: "つね、とこ", m: "Selalu, biasa, konstan", s: 11, w: [["非常", "ひじょう", "Darurat / luar biasa"], ["日常", "にちじょう", "Sehari-hari"]] },
  { k: "非", on: "ヒ", kun: "あら・ず", m: "Bukan, tidak adil, salah", s: 8, w: [["非常口", "ひじょうぐち", "Pintu darurat"], ["是非", "ぜひ", "Pasti / harus coba"]] },
  { k: "指", on: "シ", kun: "ゆび、さ・す", m: "Jari, menunjuk", s: 9, w: [["指示", "しじ", "Petunjuk/arahan"], ["指輪", "ゆびわ", "Cincin"]] },
  { k: "定", on: "テイ、ジョウ", kun: "さだ・める", m: "Menentukan, pasti, tetap", s: 8, w: [["予定", "よてい", "Rencana jadwal"], ["定休日", "ていきゅうび", "Hari libur rutin"]] },
  { k: "期", on: "キ、ゴ", kun: "", m: "Periode, batas jangka waktu", s: 12, w: [["期間", "きかん", "Jangka waktu"], ["期待", "きたい", "Harapan besar"]] },
  { k: "限", on: "ゲン", kun: "かぎ・る", m: "Batas, membatasi", s: 9, w: [["期限", "きげん", "Batas waktu"], ["限界", "げんかい", "Batas kemampuan"]] },
  { k: "界", on: "カイ", kun: "", m: "Dunia, batas wilayah", s: 9, w: [["世界", "せかい", "Dunia"], ["限界", "げんかい", "Batas maksimal"]] },
  { k: "由", on: "ユ、ユウ", kun: "よし", m: "Asal-usul, alasan", s: 5, w: [["自由", "じゆう", "Bebas"], ["経由", "けいゆ", "Transit / via"]] },
  { k: "情", on: "ジョウ、セイ", kun: "なさ・け", m: "Perasaan, informasi, iba", s: 11, w: [["感情", "かんじょう", "Emosi"], ["事情", "じじょう", "Situasi/kondisi"]] },
  { k: "感", on: "カン", kun: "かん・じる", m: "Merasakan, kesan batin", s: 13, w: [["感想", "かんそう", "Kesan/opini"], ["感動", "かんどう", "Terharu"]] },
  { k: "想", on: "ソウ、ソ", kun: "おも・う", m: "Gagasan, angan-angan", s: 13, w: [["想像", "そうぞう", "Imajinasi"], ["理想", "りそう", "Cita-cita ideal"]] },
  { k: "愛", on: "アイ", kun: "いと・しい", m: "Cinta, kasih sayang", s: 13, w: [["愛情", "あいじょう", "Kasih sayang"], ["恋愛", "れんあい", "Percintaan"]] },
  { k: "恋", on: "レン", kun: "こ・う、こい", m: "Asmara, rindu, jatuh cinta", s: 10, w: [["恋人", "こいびと", "Kekasih"], ["失恋", "しつれん", "Patah hati"]] },
  { k: "痛", on: "ツウ", kun: "いた・い、いた・む", m: "Sakit, nyeri", s: 12, w: [["頭痛", "ずつう", "Sakit kepala"], ["苦痛", "くつう", "Penderitaan"]] },
  { k: "苦", on: "ク", kun: "くる・しい、にが・い", m: "Pahit, menderita, susah", s: 8, w: [["苦労", "くろう", "Kerja keras/kesulitan"], ["苦手", "にがて", "Kurang mahir/lemah"]] },
  { k: "悩", on: "ノウ", kun: "なや・む", m: "Gelisah, bingung memikirkan", s: 10, w: [["悩み", "なやみ", "Beban pikiran"], ["苦悩", "くのう", "Kegalauan"]] },
  { k: "困", on: "コン", kun: "こま・る", m: "Kesulitan, bingung", s: 7, w: [["困る", "こまる", "Kesusahan"], ["困難", "こんなん", "Rintangan sulit"]] },
  { k: "難", on: "ナン", kun: "むずか・しい", m: "Sulit, sukar, bencana", s: 18, w: [["難しい", "むずかしい", "Sulit"], ["避難", "ひなん", "Evakuasi"]] },

  // 61-80
  { k: "危", on: "キ", kun: "あぶ・ない、あや・うい", m: "Bahaya, kritis", s: 6, w: [["危険", "きけん", "Berbahaya"], ["危機", "きき", "Krisis"]] },
  { k: "険", on: "ケン", kun: "けわ・しい", m: "Curam, terjal, bahaya", s: 11, w: [["保険", "ほけん", "Asuransi"], ["険しい", "けわしい", "Terjal"]] },
  { k: "防", on: "ボウ", kun: "ふせ・ぐ", m: "Mencegah, membendung", s: 7, w: [["予防", "よぼう", "Pencegahan"], ["防水", "ぼうすい", "Tahan air"]] },
  { k: "災", on: "サイ", kun: "わざわ・い", m: "Bencana, kemalangan", s: 7, w: [["火災", "かさい", "Kebakaran"], ["防災", "ぼうさい", "Mitigasi bencana"]] },
  { k: "害", on: "ガイ", kun: "", m: "Kerusakan, bahaya racun", s: 10, w: [["被害", "ひがい", "Korban/kerugian"], ["公害", "こうがい", "Pencemaran"]] },
  { k: "警", on: "ケイ", kun: "", m: "Peringatan, waspada, polisi", s: 19, w: [["警察", "けいさつ", "Kepolisian"], ["警告", "けいこく", "Peringatan keras"]] },
  { k: "察", on: "サツ", kun: "", m: "Menyelidiki, menduga", s: 14, w: [["診察", "しんさつ", "Pemeriksaan dokter"], ["観察", "かんさつ", "Observasi"]] },
  { k: "署", on: "ショ", kun: "", m: "Kantor dinas pemerintah", s: 13, w: [["警察署", "けいさつしょ", "Kantor polisi"], ["消防署", "しょうぼうしょ", "Dinas damkar"]] },
  { k: "役", on: "ヤク", kun: "", m: "Dinas kemasyarakatan", s: 7, w: [["役所", "やくしょ", "Kantor balai kota"], ["市役所", "しやくしょ", "Kantor walikota"]] },
  { k: "民", on: "ミン", kun: "たみ", m: "Rakyat, warga", s: 5, w: [["市民", "しみん", "Warga kota"], ["国民", "こくみん", "Rakyat bangsa"]] },
  { k: "票", on: "ヒョウ", kun: "", m: "Surat suara, tiket/kupon", s: 11, w: [["投票", "とうひょう", "Pemungutan suara"], ["得票", "とくひょう", "Perolehan suara"]] },
  { k: "投", on: "トウ", kun: "な・げる", m: "Melempar, menaruh dana", s: 7, w: [["投げる", "なげる", "Melempar"], ["投資", "とうし", "Investasi modal"]] },
  { k: "資", on: "シ", kun: "", m: "Modal, aset, bahan baku", s: 13, w: [["資格", "しかく", "Sertifikasi/kualifikasi"], ["資料", "しりょう", "Materi/dokumen"]] },
  { k: "格", on: "カク、コウ", kun: "", m: "Status, peringkat, kelayakan", s: 10, w: [["合格", "ごうかく", "Lulus ujian"], ["価格", "かかく", "Harga barang"]] },
  { k: "価", on: "カ", kun: "あたい", m: "Nilai, harga patokan", s: 8, w: [["物価", "ぶっか", "Harga kebutuhan hidup"], ["評価", "ひょうか", "Evaluasi/apresiasi"]] },
  { k: "商", on: "ショウ", kun: "あきな・う", m: "Berdagang, berniaga", s: 11, w: [["商品", "しょうひん", "Komoditas barang"], ["商業", "しょうぎょう", "Perdagangan"]] },
  { k: "品", on: "ヒン", kun: "しな", m: "Barang, kualitas martabat", s: 9, w: [["作品", "さくひん", "Karya seni"], ["食品", "しょくひん", "Bahan makanan"]] },
  { k: "買", on: "バイ", kun: "か・う", m: "Membeli", s: 12, w: [["売買", "ばいばい", "Jual beli"], ["買い物", "かいもの", "Belanja"]] },
  { k: "売", on: "バイ", kun: "う・る、う・れる", m: "Menjual, laku", s: 7, w: [["自動販売機", "じどうはんばいき", "Mesin penjual otomatis"], ["売り切れ", "うりきれ", "Habis terjual"]] },
  { k: "払", on: "フツ", kun: "はら・う", m: "Membayar, menyapu bersih", s: 5, w: [["支払い", "しはらい", "Pembayaran"], ["払い戻し", "はらいもどし", "Pengembalian uang"]] },

  // 81-100
  { k: "税", on: "ゼイ", kun: "", m: "Pajak", s: 12, w: [["消費税", "しょうひぜい", "PPN"], ["税金", "ぜいきん", "Uang pajak"]] },
  { k: "費", on: "ヒ", kun: "つい・やす", m: "Biaya, ongkos pengeluaran", s: 12, w: [["費用", "ひよう", "Biaya total"], ["交通費", "こうつうひ", "Ongkos transportasi"]] },
  { k: "借", on: "シャク", kun: "か・りる", m: "Meminjam", s: 10, w: [["借金", "しゃっきん", "Hutang uang"], ["借りる", "かりる", "Meminjam"]] },
  { k: "貸", on: "タイ", kun: "か・す", m: "Meminjamkan, menyewakan", s: 12, w: [["貸出", "かしだし", "Peminjaman"], ["賃貸", "ちんたい", "Sewa menyewa"]] },
  { k: "貸", on: "タイ", kun: "か・す", m: "Pemberian pinjaman", s: 12, w: [["貸付", "かしつけ", "Kredit/pinjaman"], ["貸家", "かしや", "Rumah kontrakan"]] },
  { k: "賃", on: "チン", kun: "", m: "Upah, sewa ongkos", s: 13, w: [["家賃", "やちん", "Uang sewa rumah"], ["運賃", "うんちん", "Tarif ongkos kirim/tiket"]] },
  { k: "預", on: "ヨ", kun: "あず・ける、あず・かる", m: "Menitipkan, menyimpan", s: 13, w: [["預金", "よきん", "Tabungan bank"], ["預かる", "あずかる", "Menjaga titipan"]] },
  { k: "貯", on: "チョ", kun: "た・める", m: "Menimbun, menabung", s: 12, w: [["貯金", "ちょきん", "Menabung uang"], ["貯蔵", "ちょぞう", "Penyimpanan stok"]] },
  { k: "得", on: "トク", kun: "え・る", m: "Memperoleh, untung", s: 11, w: [["得意", "とくい", "Keahlian unggul"], ["納得", "なっとく", "Paham/menerima"]] },
  { k: "失", on: "シツ", kun: "うしな・う", m: "Hilang, luput", s: 5, w: [["失敗", "しっぱい", "Kegagalan"], ["失望", "しつぼう", "Kekecewaan"]] },
  { k: "礼", on: "レイ、ライ", kun: "", m: "Tata krama, ucapan syukur", s: 5, w: [["お礼", "おれい", "Ucapan terima kasih"], ["礼儀", "れいぎ", "Kesopanan"]] },
  { k: "儀", on: "ギ", kun: "", m: "Upacara, etiket kesopanan", s: 15, w: [["儀式", "ぎしき", "Upacara resmi"], ["マナー・礼儀", "れいぎ", "Sopan santun"]] },
  { k: "謝", on: "シャ", kun: "あやま・る", m: "Meminta maaf, berterima kasih", s: 17, w: [["謝る", "あやまる", "Minta maaf"], ["感謝", "かんしゃ", "Rasa syukur"]] },
  { k: "敬", on: "ケイ", kun: "うやま・う", m: "Menghormati, takzim", s: 12, w: [["敬語", "けいご", "Bahasa sopan/keigo"], ["尊敬", "そんけい", "Rasa hormat"]] },
  { k: "尊", on: "ソン", kun: "とうと・い", m: "Mulia, berharga tinggi", s: 12, w: [["尊重", "そんちょう", "Menghargai hak"], ["尊い", "とうとい", "Amat mulia"]] },
  { k: "重", on: "ジュウ、チョウ", kun: "おも・い、かさ・なる", m: "Berat, rangkap, penting", s: 9, w: [["重要", "じゅうよう", "Penting sekali"], ["体重", "たいじゅう", "Berat badan"]] },
  { k: "軽", on: "ケイ", kun: "かる・い", m: "Ringan, sepele", s: 12, w: [["手軽", "てがる", "Praktis/ringan"], ["軽食", "けいしょく", "Kudapan ringan"]] },
  { k: "深", on: "シン", kun: "ふか・い", m: "Dalam, mendalam", s: 11, w: [["深刻", "しんこく", "Gawat / serius"], ["水深", "すいしん", "Kedalaman air"]] },
  { k: "浅", on: "セン", kun: "あさ・い", m: "Dangkal", s: 9, w: [["浅い", "あさい", "Dangkal"], ["浅薄", "せんぱく", "Ceteka nalar"]] },
  { k: "刻", on: "コク", kun: "きざ・む", m: "Mengukir, mencacah waktu", s: 8, w: [["時刻", "じこく", "Waktu tepat"], ["遅刻", "ちこく", "Keterlambatan"]] },

  // 101-120
  { k: "守", on: "シュ、ス", kun: "まも・る", m: "Melindungi, mematuhi", s: 6, w: [["留守", "るす", "Meninggalkan rumah"], ["守る", "まもる", "Menjaga janji"]] },
  { k: "受", on: "ジュ", kun: "う・ける", m: "Menerima, menempuh", s: 8, w: [["受付", "うけつけ", "Resepsionis"], ["受験", "じゅけん", "Mengikuti ujian"]] },
  { k: "付", on: "フ", kun: "つ・ける、つ・く", m: "Menempelkan, menyertakan", s: 5, w: [["片付ける", "かたづける", "Merapikan"], ["日付", "ひづけ", "Tanggal"]] },
  { k: "取", on: "シュ", kun: "と・る", m: "Mengambil", s: 8, w: [["受取", "うけとり", "Tanda terima"], ["取消", "とりけし", "Pembatalan"]] },
  { k: "消", on: "ショウ", kun: "き・える、け・す", m: "Padam, menghapus", s: 10, w: [["消しゴム", "けしゴム", "Penghapus"], ["消化", "しょうか", "Pencernaan"]] },
  { k: "防", on: "ボウ", kun: "ふせ・ぐ", m: "Menangkal bahaya", s: 7, w: [["消防", "しょうぼう", "Pemadam api"], ["防衛", "ぼうえい", "Pertahanan"]] },
  { k: "救", on: "キュウ", kun: "すく・う", m: "Menolong, menyelamatkan", s: 11, w: [["救急車", "きゅうきゅうしゃ", "Ambulans"], ["救助", "きゅうじょ", "Penyelamatan SAR"]] },
  { k: "助", on: "ジョ", kun: "たす・かる、たす・ける", m: "Membantu, terselamatkan", s: 7, w: [["助ける", "たすける", "Menolong orang"], ["助手", "じょしゅ", "Asisten staf"]] },
  { k: "招", on: "ショウ", kun: "まね・く", m: "Mengundang, mengajak", s: 8, w: [["招待", "しょうたい", "Undangan pesta"], ["招く", "まねく", "Mengundang"]] },
  { k: "待", on: "タイ", kun: "ま・つ", m: "Menunggu", s: 9, w: [["待合室", "まちあいしつ", "Ruang tunggu"], ["期待", "きたい", "Harapan"]] },
  { k: "呼", on: "コ", kun: "よ・ぶ", m: "Memanggil, bernapas", s: 8, w: [["呼ぶ", "よぶ", "Memanggil"], ["呼吸", "こきゅう", "Pernapasan"]] },
  { k: "吸", on: "キュウ", kun: "す・う", m: "Menghisap, menyedot", s: 6, w: [["吸う", "すう", "Menghisap rokok"], ["吸収", "きゅうしゅう", "Penyerapan"]] },
  { k: "収", on: "シュウ", kun: "おさ・める", m: "Menampung, memperoleh penghasilan", s: 4, w: [["収入", "しゅうにゅう", "Penghasilan"], ["領収書", "りょうしゅうしょ", "Kuitansi"]] },
  { k: "領", on: "リョウ", kun: "", m: "Wilayah, memimpin", s: 14, w: [["大統領", "だいとうりょう", "Presiden"], ["領事館", "りょうじかん", "Konsulat"]] },
  { k: "導", on: "ドウ", kun: "みちび・く", m: "Membimbing, menuntun", s: 15, w: [["指導", "しどう", "Bimbingan arahan"], ["導入", "どうにゅう", "Penerapan awal"]] },
  { k: "指", on: "シ", kun: "さ・す", m: "Menunjuk arah", s: 9, w: [["指導者", "しどうしゃ", "Pemimpin/pelatih"], ["指定", "してい", "Penunjukan"]] },
  { k: "向", on: "コウ", kun: "む・く、む・かう", m: "Menghadap, menuju", s: 6, w: [["傾向", "けいこう", "Kecenderungan tren"], ["方向", "ほうこう", "Arah haluan"]] },
  { k: "傾", on: "ケイ", kun: "かたむ・く", m: "Miring, condong", s: 13, w: [["傾向", "けいこう", "Tren orientasi"], ["傾斜", "けいしゃ", "Kemiringan lereng"]] },
  { k: "横", on: "オウ", kun: "よこ", m: "Mendatar, horizontal, samping", s: 15, w: [["横断歩道", "おうだんほどう", "Zebra cross"], ["横", "よこ", "Sebelah / samping"]] },
  { k: "断", on: "ダン", kun: "", m: "Melintasi garis", s: 11, w: [["横断", "おうだん", "Menyeberang jalan"], ["診断", "しんだん", "Diagnosis medis"]] },

  // 121-140
  { k: "側", on: "ソク", kun: "がわ、そば", m: "Sisi, sebelah pihak", s: 11, w: [["右側", "みぎがわ", "Sisi kanan"], ["両側", "りょうがわ", "Kedua belah sisi"]] },
  { k: "端", on: "タン", kun: "はし、は", m: "Ujung, tepi", s: 14, w: [["先端", "せんたん", "Teknologi tercanggih"], ["端", "はし", "Ujung pinggir"]] },
  { k: "先", on: "セン", kun: "さき、ま・ず", m: "Dulu, depan, ujung", s: 6, w: [["先輩", "せんぱい", "Senior"], ["先月", "せんげつ", "Bulan lalu"]] },
  { k: "輩", on: "ハイ", kun: "", m: "Rekan segenerasi", s: 15, w: [["後輩", "こうはい", "Junior"], ["同輩", "どうはい", "Teman sebaya"]] },
  { k: "後", on: "ゴ、コウ", kun: "うし・ろ、あと、おく・れる", m: "Belakang, setelah, terlambat", s: 9, w: [["午後", "ごご", "Sore/PM"], ["後半", "こうはん", "Babak kedua"]] },
  { k: "前", on: "ゼン", kun: "まえ", m: "Depan, sebelum", s: 9, w: [["午前", "ごぜん", "Pagi/AM"], ["前後", "ぜんご", "Depan belakang / kira-kira"]] },
  { k: "直", on: "チョク、ジキ", kun: "ただ・ちに、なお・す", m: "Lurus, segera, memperbaiki", s: 8, w: [["直接", "ちょくせつ", "Secara langsung"], ["正直", "しょうじき", "Jujur tulus"]] },
  { k: "接", on: "セツ", kun: "つ・ぐ", m: "Menempel, kontak", s: 11, w: [["接近", "せっきん", "Mendekat"], ["接客", "せっきゃく", "Pelayanan pembeli"]] },
  { k: "近", on: "キン", kun: "ちか・い", m: "Dekat", s: 7, w: [["近所", "きんじょ", "Lingkungan tetangga"], ["最近", "さいきん", "Akhir-akhir ini"]] },
  { k: "遠", on: "エン、オン", kun: "とお・い", m: "Jauh", s: 13, w: [["遠慮", "えんりょ", "Sungkan / menahan diri"], ["遠足", "えんそく", "Piknik sekolah"]] },
  { k: "慮", on: "リョ", kun: "", m: "Pertimbangan, rasa cemas", s: 15, w: [["配慮", "はいりょ", "Perhatian kepedulian"], ["考慮", "こうりょ", "Pertimbangan mendalam"]] },
  { k: "配", on: "ハイ", kun: "くば・る", m: "Membagikan, mengatur", s: 10, w: [["心配", "しんぱい", "Cemas"], ["配達", "はいたつ", "Pengantaran paket"]] },
  { k: "達", on: "タツ", kun: "たち", m: "Mencapai, menguasai, jamak", s: 12, w: [["友達", "ともだち", "Sahabat teman"], ["発達", "はったつ", "Perkembangan fisik/sistem"]] },
  { k: "送", on: "ソウ", kun: "おく・る", m: "Mengirim, mengantar", s: 9, w: [["送金", "そうきん", "Transfer uang"], ["見送り", "みおくり", "Mengantar perpisahan"]] },
  { k: "返", on: "ヘン", kun: "かえ・す、かえ・る", m: "Mengembalikan, membalas", s: 7, w: [["返事", "へんじ", "Balasan jawaban"], ["返却", "へんきゃく", "Pengembalian barang"]] },
  { k: "却", on: "キャク", kun: "", m: "Mundur, menolak balik", s: 7, w: [["却下", "きゃっか", "Ditolak permohonannya"], ["償却", "しょうきゃく", "Amortisasi"]] },
  { k: "折", on: "セツ", kun: "お・る、お・れる", m: "Melipat, patah", s: 7, w: [["折り紙", "おりがみ", "Origami"], ["骨折", "こっせつ", "Patah tulang"]] },
  { k: "骨", on: "コツ", kun: "ほね", m: "Tulang, kerangka", s: 10, w: [["骨", "ほね", "Tulang"], ["骨組み", "ほねぐみ", "Kerangka struktur"]] },
  { k: "組", on: "ソ", kun: "く・む、くみ", m: "Menyusun, regu, kelompok", s: 11, w: [["組織", "そしき", "Organisasi"], ["番組", "ばんぐみ", "Acara siaran TV"]] },
  { k: "織", on: "ショク、シキ", kun: "お・る", m: "Menenun, merajut", s: 18, w: [["織物", "おりもの", "Kain tenun"], ["組織的", "そしきてき", "Secara sistematis terorganisir"]] },

  // 141-160
  { k: "成", on: "セイ、ジョウ", kun: "な・る", m: "Menjadi, tercapai, tumbuh", s: 6, w: [["成功", "せいこう", "Kesuksesan"], ["完成", "かんせい", "Penyelesaian paripurna"]] },
  { k: "功", on: "コウ", kun: "いさお", m: "Prestasi, jasa gemilang", s: 5, w: [["功績", "こうせき", "Jasa besar"], ["成功者", "せいこうしゃ", "Orang sukses"]] },
  { k: "完", on: "カン", kun: "", m: "Lengkap, sempurna", s: 7, w: [["完全", "かんぜん", "Sempurna utuh"], ["完了", "かんりょう", "Tuntas selesai"]] },
  { k: "了", on: "リョウ", kun: "", m: "Selesai, paham", s: 2, w: [["了解", "りょうかい", "Dimengerti/roger"], ["終了", "しゅうりょう", "Berakhir"]] },
  { k: "終", on: "シュウ", kun: "お・わる、お・える", m: "Selesai, penghabisan", s: 11, w: [["終点", "しゅうてん", "Pemberhentian terakhir"], ["終電", "しゅうでん", "Kereta terakhir malam"]] },
  { k: "始", on: "シ", kun: "はじ・まる、はじ・める", m: "Mulai", s: 8, w: [["開始", "かいし", "Dimulai"], ["始発", "しはつ", "Kereta pertama subuh"]] },
  { k: "開", on: "カイ", kun: "ひら・く、あ・ける", m: "Membuka", s: 12, w: [["開店", "かいてん", "Buka toko"], ["開発", "かいはつ", "Pengembangan teknologi"]] },
  { k: "閉", on: "ヘイ", kun: "と・じる、し・める", m: "Menutup", s: 11, w: [["閉店", "へいてん", "Tutup toko"], ["閉会", "へいかい", "Penutupan acara"]] },
  { k: "点", on: "テン", kun: "つ・ける", m: "Titik, nilai skor", s: 9, w: [["交差点", "こうさてん", "Persimpangan jalan"], ["欠点", "けってん", "Kekurangan/kelemahan"]] },
  { k: "交", on: "コウ", kun: "まじ・わる、か・わす", m: "Silang, interaksi, bertukar", s: 6, w: [["交流", "こうりゅう", "Pertukaran budaya"], ["交渉", "こうしょう", "Negosiasi"]] },
  { k: "差", on: "サ", kun: "さ・す", m: "Selisih, perbedaan", s: 10, w: [["格差", "かくさ", "Kesenjangan"], ["時差", "じさ", "Perbedaan zona waktu"]] },
  { k: "欠", on: "ケツ", kun: "か・ける", m: "Kurang, absen, cacat", s: 4, w: [["欠席", "けっせき", "Absen ketidakhadiran"], ["不可欠", "ふかけつ", "Mutlak diperlukan"]] },
  { k: "席", on: "セキ", kun: "", m: "Tempat duduk resmi", s: 10, w: [["空席", "くうせき", "Kursi kosong"], ["満席", "まんせき", "Penuh terisi"]] },
  { k: "空", on: "クウ", kun: "そら、あ・く、から", m: "Langit, kosong", s: 8, w: [["空港", "くうこう", "Bandara udara"], ["空気", "くうき", "Udara hawa"]] },
  { k: "港", on: "コウ", kun: "みなと", m: "Pelabuhan", s: 12, w: [["出港", "しゅっこう", "Kapal berlayar keluar"], ["港町", "みなとまち", "Kota pelabuhan"]] },
  { k: "湾", on: "ワン", kun: "いりえ", m: "Teluk perairan", s: 12, w: [["東京湾", "とうきょうわん", "Teluk Tokyo"], ["湾岸", "わんがん", "Pesisir teluk"]] },
  { k: "岸", on: "ガン", kun: "きし", m: "Pesisir, tepi pantai/sungai", s: 8, w: [["海岸", "かいがん", "Tepi laut"], ["対岸", "たいがん", "Tepi seberang"]] },
  { k: "陸", on: "リク", kun: "おか", m: "Daratan benua", s: 11, w: [["着陸", "ちゃくりく", "Pendaratan pesawat"], ["大陸", "たいりく", "Benua daratan besar"]] },
  { k: "着", on: "チャク、ジャク", kun: "つ・く、き・る", m: "Tiba, mengenakan baju", s: 12, w: [["到着", "とうちゃく", "Kedatangan"], ["上着", "うわぎ", "Jaket/baju luar"]] },
  { k: "倒", on: "トウ", kun: "たお・れる、たお・す", m: "Tumbang, roboh, bangkrut", s: 10, w: [["倒産", "とうさん", "Kebangkrutan bisnis"], ["倒れる", "たおれる", "Tumbang pingsan"]] },

  // 161-180
  { k: "産", on: "サン", kun: "う・む、う・まれる", m: "Melahirkan, memproduksi", s: 11, w: [["産業", "さんぎょう", "Sektor industri"], ["生産", "せいさん", "Produksi"]] },
  { k: "業", on: "ギョウ、ゴウ", kun: "わざ", m: "Pekerjaan industri, usaha", s: 13, w: [["授業", "じゅぎょう", "Pelajaran kelas"], ["残業", "ざんぎょう", "Lembur kerja"]] },
  { k: "残", on: "ザン", kun: "のこ・る、のこ・す", m: "Tersisa, meninggalkan", s: 10, w: [["残念", "ざんねん", "Sangat disayangkan"], ["残り", "のこり", "Sisa"]] },
  { k: "念", on: "ネン", kun: "", m: "Pikiran, hasrat batin", s: 8, w: [["記念", "きねん", "Peringatan memoratorium"], ["信念", "しんねん", "Keyakinan teguh"]] },
  { k: "記", on: "キ", kun: "しる・す", m: "Mencatat, menorehkan", s: 10, w: [["記事", "きじ", "Artikel berita"], ["記入", "きにゅう", "Pengisian formulir"]] },
  { k: "録", on: "ロク", kun: "", m: "Rekaman data, arsip", s: 16, w: [["記録", "きろく", "Rekor/catatan"], ["登録", "とうろく", "Pendaftaran akun"]] },
  { k: "登", on: "トウ、ト", kun: "のぼ・る", m: "Mendaki, terdaftar naik", s: 12, w: [["登山", "とざん", "Mendaki gunung"], ["登場", "とうじょう", "Tampil di panggung"]] },
  { k: "録", on: "ロク", kun: "", m: "Perekaman", s: 16, w: [["録音", "ろくおん", "Rekaman suara"], ["録画", "ろくが", "Rekaman video"]] },
  { k: "音", on: "オン、イン", kun: "おと、ね", m: "Bunyi nada, suara", s: 9, w: [["音楽", "おんがく", "Musik"], ["発音", "はつおん", "Pelafalan pengucapan"]] },
  { k: "楽", on: "ガク、ラク", kun: "たの・しい", m: "Gembira, nyaman, santai", s: 13, w: [["気楽", "きらく", "Santai tanpa beban"], ["楽しみ", "たのしみ", "Kesenangan antusias"]] },
  { k: "試", on: "シ", kun: "こころ・みる、ため・す", m: "Mencoba, menguji", s: 13, w: [["試験", "しけん", "Ujian pengetesan"], ["試合", "しあい", "Pertandingan turnamen"]] },
  { k: "験", on: "ケン、ゲン", kun: "", m: "Bukti uji coba, hasil", s: 18, w: [["実験", "じっけん", "Eksperimen lab"], ["体験", "たいけん", "Pengalaman langsung"]] },
  { k: "合", on: "ゴウ、ガッ", kun: "あ・う、あ・わせる", m: "Cocok, bergabung, padu", s: 6, w: [["都合", "つごう", "Kenyamanan waktu/kondisi"], ["場合", "ばあい", "Situasi kejadian"]] },
  { k: "実", on: "ジツ", kun: "み、みの・る", m: "Nyata, buah hasil", s: 8, w: [["実際", "じっさい", "Kenyataan riil"], ["真実", "しんじつ", "Kebenaran sejati"]] },
  { k: "真", on: "シン", kun: "ま、まこと", m: "Murni, sejati", s: 10, w: [["写真", "しゃしん", "Foto potret"], ["真面目", "まじめ", "Rajin tekun/jujur"]] },
  { k: "写", on: "シャ", kun: "うつ・す、うつ・る", m: "Menyalin, memotret", s: 5, w: [["写生", "しゃせい", "Menggambar sketsa"], ["複写", "ふくしゃ", "Fotokopi"]] },
  { k: "複", on: "フク", kun: "", m: "Ganda, majemuk", s: 14, w: [["複雑", "ふくざつ", "Rumit kompleks"], ["複数", "ふくすう", "Jumlah jamak"]] },
  { k: "雑", on: "ザツ、ゾウ", kun: "ま・ぜる", m: "Campur baur, aneka", s: 14, w: [["雑誌", "ざっし", "Majalah"], ["雑音", "ざつおん", "Suara berisik / noise"]] },
  { k: "誌", on: "シ", kun: "", m: "Catatan berkala, buletin", s: 14, w: [["週刊誌", "しゅうかんし", "Majalah mingguan"], ["日誌", "にっし", "Buku harian jurnal"]] },
  { k: "刊", on: "カン", kun: "", m: "Menerbitkan, cetakan publikasi", s: 5, w: [["朝刊", "ちょうかん", "Koran pagi"], ["夕刊", "ゆうかん", "Koran sore"]] },

  // 181-200
  { k: "朝", on: "チョウ", kun: "あさ", m: "Pagi hari, dinasti", s: 12, w: [["朝食", "ちょうしょく", "Sarapan pagi"], ["今朝", "けさ", "Tadi pagi"]] },
  { k: "昼", on: "チュウ", kun: "ひる", m: "Siang hari", s: 9, w: [["昼食", "ちゅうしょく", "Makan siang"], ["昼休み", "ひるやすみ", "Istirahat siang"]] },
  { k: "夜", on: "ヤ", kun: "よる、よ", m: "Malam hari", s: 8, w: [["夜景", "やけい", "Pemandangan malam"], ["今夜", "こんや", "Malam ini"]] },
  { k: "晩", on: "バン", kun: "", m: "Senja malam", s: 12, w: [["今晩", "こんばん", "Malam ini"], ["晩ご飯", "ばんごはん", "Makan malam"]] },
  { k: "景", on: "ケイ", kun: "", m: "Panorama pemandangan, kondisi", s: 12, w: [["景色", "けしき", "Pemandangan alam"], ["不景気", "ふけいき", "Resesi lesu"]] },
  { k: "色", on: "ショク、シキ", kun: "いろ", m: "Warna, corak rupa", s: 6, w: [["特色", "とくしょく", "Ciri khas unik"], ["茶色", "ちゃいろ", "Cokelat"]] },
  { k: "特", on: "トク", kun: "", m: "Spesial, istimewa khusus", s: 10, w: [["特別", "とくべつ", "Istimewa"], ["特に", "とくに", "Khususnya"]] },
  { k: "別", on: "ベツ", kun: "わか・れる", m: "Berpisah, lain, berbeda", s: 7, w: [["差別", "さべつ", "Diskriminasi"], ["別れる", "わかれる", "Berpisah"]] },
  { k: "差", on: "サ", kun: "さ・す", m: "Perbedaan diskriminatif", s: 10, w: [["男女差", "だんじょさ", "Perbedaan gender"], ["大差", "たいさ", "Perbedaan mencolok"]] },
  { k: "有", on: "ユウ、ウ", kun: "あ・る", m: "Ada, memiliki", s: 6, w: [["有名", "ゆうめい", "Terkenal"], ["有料", "ゆうりょう", "Berbayar"]] },
  { k: "名", on: "メイ、ミョウ", kun: "な", m: "Nama, reputasi", s: 6, w: [["名所", "めいしょ", "Tempat wisata kondang"], ["名字", "みょうじ", "Marga / nama keluarga"]] },
  { k: "利", on: "リ", kun: "き・く", m: "Manfaat faedah, bunga bank", s: 7, w: [["便利", "べんり", "Praktis nyaman"], ["利益", "りえき", "Keuntungan laba"]] },
  { k: "便", on: "ベン、ビン", kun: "たよ・り", m: "Penerbangan/pos, kemudahan", s: 9, w: [["郵便", "ゆうびん", "Pos surat"], ["航空便", "こうくうびん", "Surat udara pos"]] },
  { k: "郵", on: "ユウ", kun: "", m: "Pos jawatan", s: 11, w: [["郵便局", "ゆうびんきょく", "Kantor pos"], ["郵送", "ゆうそう", "Pengiriman pos"]] },
  { k: "局", on: "キョク", kun: "", m: "Biro jawatan, kantor stasiun", s: 7, w: [["結局", "けっきょく", "Pada akhirnya"], ["薬局", "やっきょく", "Apotek"]] },
  { k: "結", on: "ケツ", kun: "むす・ぶ、ゆ・わえる", m: "Mengikat, menyimpulkan", s: 12, w: [["結婚", "けっこん", "Pernikahan"], ["結果", "けっか", "Hasil akibat"]] },
  { k: "果", on: "カ", kun: "は・たす、くだ", m: "Buah, mewujudkan", s: 8, w: [["果物", "くだもの", "Buah-buahan"], ["効果", "こうか", "Khasiat efektivitas"]] },
  { k: "効", on: "コウ", kun: "き・く", m: "Manjur, khasiat ampuh", s: 8, w: [["有効", "ゆうこう", "Berlaku sah / efektif"], ["無効", "むこう", "Tidak berlaku invalid"]] },
  { k: "無", on: "ム、ブ", kun: "な・い", m: "Tiada, nihil", s: 12, w: [["無料", "むりょう", "Gratis cuma-cuma"], ["無理", "むり", "Mustahil / memaksa diri"]] },
  { k: "料", on: "リョウ", kun: "", m: "Biaya, takaran materi", s: 10, w: [["料金", "りょうきん", "Tarif biaya"], ["原料", "げんりょう", "Bahan mentah baku"]] },

  // 201-220
  { k: "原", on: "ゲン", kun: "はら", m: "Padang, asal mula orisinil", s: 10, w: [["原因", "げんいん", "Penyebab mula"], ["野原", "のはら", "Padang rumput"]] },
  { k: "因", on: "イン", kun: "よ・る", m: "Faktor penyebab", s: 6, w: [["要因", "よういん", "Faktor penentu"], ["死因", "しいん", "Penyebab kematian"]] },
  { k: "要", on: "ヨウ", kun: "い・る", m: "Perlu, penting utama", s: 9, w: [["必要", "ひつよう", "Dibutuhkan"], ["要点", "ようてん", "Poin inti penting"]] },
  { k: "必", on: "ヒツ", kun: "かなら・ず", m: "Pasti, mutlak niscaya", s: 5, w: [["必ず", "かならず", "Pasti niscaya"], ["必死", "ひっし", "Mati-matian gigih"]] },
  { k: "死", on: "シ", kun: "し・ぬ", m: "Mati, wafat", s: 6, w: [["死亡", "しぼう", "Meninggal dunia"], ["死者", "ししゃ", "Korban tewas"]] },
  { k: "亡", on: "ボウ、モウ", kun: "な・くなる", m: "Wafat, hilang sirna", s: 3, w: [["亡くなる", "なくなる", "Meninggal"], ["未亡人", "みぼうじん", "Janda"]] },
  { k: "急", on: "キュウ", kun: "いそ・ぐ", m: "Cepat mendesak, bergegas", s: 9, w: [["急行", "きゅうこう", "Kereta ekspres"], ["大急ぎ", "おおいそぎ", "Sangat terburu-buru"]] },
  { k: "速", on: "ソク", kun: "はや・い、すみ・やか", m: "Laju cepat", s: 10, w: [["速度", "そくど", "Kecepatan speed"], ["急速", "きゅうそく", "Sangat pesat"]] },
  { k: "遅", on: "チ", kun: "おく・れる、おそ・い", m: "Lambat, terlambat", s: 12, w: [["遅延", "ちえん", "Penundaan jadwal"], ["手遅れ", "ておくれ", "Sudah terlambat nasi jadi bubur"]] },
  { k: "延", on: "エン", kun: "の・びる、の・ばす", m: "Memperpanjang, molor", s: 8, w: [["延期", "えんき", "Penundaan tanggal"], ["延長", "えんちょう", "Perpanjangan waktu"]] },
  { k: "長", on: "チョウ", kun: "なが・い", m: "Panjang, pimpinan", s: 8, w: [["部長", "ぶちょう", "Kepala divisi departemen"], ["市長", "しちょう", "Walikota"]] },
  { k: "短", on: "タン", kun: "みじか・い", m: "Pendek, singkat", s: 12, w: [["短気", "たんき", "Mudah marah pemarah"], ["短所", "たんしょ", "Kekurangan diri"]] },
  { k: "所", on: "ショ", kun: "ところ", m: "Tempat, bagian titik", s: 8, w: [["場所", "ばしょ", "Tempat lokasi"], ["長所", "ちょうしょ", "Kelebihan keunggulan"]] },
  { k: "場", on: "ジョウ", kun: "ば", m: "Area lokasi arena", s: 12, w: [["広場", "ひろば", "Alun-alun lapangan"], ["立場", "たちば", "Posisi sudut pandang"]] },
  { k: "立", on: "リツ、リュウ", kun: "た・つ、た・てる", m: "Berdiri, mendirikan", s: 5, w: [["自立", "じりつ", "Mandiri independen"], ["国立", "こくりつ", "Negeri/nasional"]] },
  { k: "座", on: "ザ", kun: "すわ・る", m: "Duduk, teater konstelasi", s: 10, w: [["座席", "ざせき", "Tempat duduk"], ["口座", "こうざ", "Rekening bank"]] },
  { k: "口", on: "コウ、ク", kun: "くち", m: "Mulut, pintu masuk, bukaan", s: 3, w: [["入口", "いりぐち", "Pintu masuk"], ["窓口", "まどぐち", "Loket pelayanan"]] },
  { k: "窓", on: "ソウ", kun: "まど", m: "Jendela", s: 11, w: [["同窓会", "どうそうかい", "Reuni alumni"], ["車窓", "しゃそう", "Jendela kereta/kendaraan"]] },
  { k: "車", on: "シャ", kun: "くるま", m: "Kendaraan mobil roda", s: 7, w: [["駐車場", "ちゅうしゃじょう", "Tempat parkir"], ["電車", "でんしゃ", "Kereta listrik"]] },
  { k: "駐", on: "チュウ", kun: "", m: "Parkir, tinggal sementara", s: 15, w: [["駐輪場", "ちゅうりんじょう", "Tempat parkir sepeda"], ["駐車違反", "ちゅうしゃいはん", "Pelanggaran parkir"]] },

  // 221-240
  { k: "輪", on: "リン", kun: "わ", m: "Roda, lingkaran cincin", s: 15, w: [["五輪", "ごりん", "Olimpiade"], ["車輪", "しゃりん", "Roda gerobak/kendaraan"]] },
  { k: "違", on: "イ", kun: "ちが・う、ちが・える", m: "Berbeda, keliru, melanggar", s: 13, w: [["間違える", "まちがえる", "Membuat kesalahan"], ["違反", "いはん", "Pelanggaran aturan"]] },
  { k: "反", on: "ハン、ホン", kun: "そ・る", m: "Menentang, membalik", s: 4, w: [["反対", "はんたい", "Tidak setuju lawan"], ["反省", "はんせい", "Mawas diri introspeksi"]] },
  { k: "省", on: "ショウ、セイ", kun: "はぶ・く、かえり・みる", m: "Kementerian, menghemat, merenungi", s: 9, w: [["文部科学省", "もんぶかがくしょう", "Kemendikbud Jepang"], ["省エネ", "しょうエネ", "Hemat energi"]] },
  { k: "対", on: "タイ、ツイ", kun: "", m: "Berhadapan, lawan tanding", s: 7, w: [["対象", "たいしょう", "Target sasaran objek"], ["応対", "おうたい", "Menerima melayani tamu"]] },
  { k: "応", on: "オウ", kun: "こた・える", m: "Menanggapi, memenuhi respons", s: 7, w: [["応援", "おうえん", "Dukungan sorak sorai"], ["応用", "おうよう", "Aplikasi terapan"]] },
  { k: "援", on: "エン", kun: "", m: "Membantu menolong menyokong", s: 12, w: [["支援", "しえん", "Dukungan donasi sokongan"], ["救援", "きゅうえん", "Pertolongan darurat SAR"]] },
  { k: "助", on: "ジョ", kun: "すけ", m: "Bantuan pembantu", s: 7, w: [["救助隊", "きゅうじょたい", "Regu penyelamat"], ["援助", "えんじょ", "Bantuan subsidi finansial"]] },
  { k: "隊", on: "タイ", kun: "", m: "Pasukan, regu kontingen", s: 12, w: [["部隊", "ぶたい", "Kesatuan korps militer"], ["隊員", "たいいん", "Anggota regu tim"]] },
  { k: "員", on: "イン", kun: "", m: "Anggota personel", s: 10, w: [["会社員", "かいしゃいん", "Pegawai kantor swasta"], ["全員", "ぜんいん", "Semua anggota tanpa kecuali"]] },
  { k: "全", on: "ゼン", kun: "まった・く、すべ・て", m: "Seluruh, komplit total", s: 6, w: [["安全", "あんぜん", "Aman tenteram"], ["全国", "ぜんこく", "Seluruh penjuru negeri"]] },
  { k: "安", on: "アン", kun: "やす・い", m: "Murah, damai tenang", s: 6, w: [["安心", "あんしん", "Lega tenteram batin"], ["不安", "ふあん", "Gelisah was-was"]] },
  { k: "不", on: "フ、ブ", kun: "", m: "Tidak, bukan, defisit", s: 4, w: [["不便", "ふべん", "Kurang praktis merepotkan"], ["不足", "ふそく", "Kekurangan defisit"]] },
  { k: "足", on: "ソク", kun: "あし、た・りる", m: "Kaki, mencukupi", s: 7, w: [["足りる", "たりる", "Cukup memadai"], ["遠足", "えんそく", "Piknik tamasya"]] },
  { k: "手", on: "シュ", kun: "て、た", m: "Tangan, tenaga kerja", s: 4, w: [["歌手", "かしゅ", "Penyanyi vokal"], ["運転手", "うんてんしゅ", "Sopir pengemudi"]] },
  { k: "歌", on: "カ", kun: "うた、うた・う", m: "Lagu tembang, bernyanyi", s: 14, w: [["国歌", "こっか", "Lagu kebangsaan"], ["歌詞", "かし", "Lirik syair lagu"]] },
  { k: "詞", on: "シ", kun: "", m: "Kata partikel bait lirik", s: 12, w: [["品詞", "ひんし", "Kelas kata gramatikal"], ["名詞", "めいし", "Kata benda nomina"]] },
  { k: "動", on: "ドウ", kun: "うご・く、うご・かす", m: "Bergerak, menggerakkan", s: 11, w: [["動詞", "どうし", "Kata kerja verba"], ["運動", "うんどう", "Olahraga gerak badan"]] },
  { k: "運", on: "ウン", kun: "はこ・ぶ", m: "Mengangkut, nasib keberuntungan", s: 12, w: [["運転", "うんてん", "Menyetir berkendara"], ["幸運", "こううん", "Beruntung bernasib mujur"]] },
  { k: "幸", on: "コウ", kun: "さいわ・い、しあわ・せ", m: "Bahagia, berkah mujur", s: 8, w: [["幸せ", "しあわせ", "Kebahagiaan hidup"], ["不幸", "ふこう", "Kemalangan musibah"]] },

  // 241-260
  { k: "福", on: "フク", kun: "", m: "Kemakmuran berkah sejahtera", s: 13, w: [["幸福", "こうふく", "Kebahagiaan berkah"], ["福祉", "ふくし", "Kesejahteraan sosial"]] },
  { k: "祉", on: "シ", kun: "", m: "Kesejahteraan warga", s: 8, w: [["社会福祉", "しゃかいふくし", "Kesejahteraan sosial"], ["福祉施設", "ふくししせつ", "Fasilitas panti sosial"]] },
  { k: "社", on: "シャ", kun: "やしろ", m: "Perusahaan komunitas kuil", s: 7, w: [["社会", "しゃかい", "Masyarakat sosial"], ["神社", "じんじゃ", "Kuil Shinto"]] },
  { k: "神", on: "シン、ジン", kun: "かみ", m: "Tuhan, dewa dewi", s: 9, w: [["神道", "しんとう", "Agama Shinto"], ["神経", "しんけい", "Saraf urat batin"]] },
  { k: "道", on: "ドウ、トウ", kun: "みち", m: "Jalan lintas, ajaran tata", s: 12, w: [["歩道", "ほどう", "Trotoar pejalan"], ["柔道", "じゅうどう", "Judo beladiri"]] },
  { k: "歩", on: "ホ、ポ", kun: "ある・く、あゆ・む", m: "Berjalan melangkah", s: 8, w: [["散歩", "さんぽ", "Jalan-jalan santai"], ["進歩", "しんぽ", "Kemajuan progres pesat"]] },
  { k: "散", on: "サン", kun: "ち・る、ち・らかす", m: "Menyebar, berserakan", s: 12, w: [["解散", "かいさん", "Bubar berpisah"], ["散乱", "さんらん", "Berantakan berserakan"]] },
  { k: "解", on: "カイ、ゲ", kun: "と・く、と・ける", m: "Memecahkan teka-teki, melepas", s: 13, w: [["解決", "かいけつ", "Penyelesaian solusi"], ["解答", "かいとう", "Kunci jawaban solusi"]] },
  { k: "答", on: "トウ", kun: "こた・える、こた・え", m: "Menjawab, respons solusi", s: 12, w: [["答案", "とうあん", "Lembar jawaban ujian"], ["回答", "かいとう", "Jawaban survei tanggapan"]] },
  { k: "案", on: "アン", kun: "", m: "Rancangan usulan draf", s: 10, w: [["案内", "あんない", "Pemandu instruksi rute"], ["提案", "ていあん", "Usulan ide proposal"]] },
  { k: "内", on: "ナイ、ダイ", kun: "うち", m: "Di dalam, domestik", s: 4, w: [["案内所", "あんないじょ", "Pusat informasi pemandu"], ["国内", "こくない", "Domestik dalam negeri"]] },
  { k: "提", on: "テイ", kun: "さ・げる", m: "Menenteng, mengajukan", s: 12, w: [["提出", "ていしゅつ", "Pengumpulan berkas"], ["提供", "ていきょう", "Pemberian sponsor sajian"]] },
  { k: "供", on: "キョウ、ク", kun: "そな・える、とも", m: "Menyajikan, menemani anak", s: 8, w: [["子供", "こども", "Anak kecil"], ["供給", "きょうきゅう", "Pasokan supply"]] },
  { k: "給", on: "キュウ", kun: "たま・う", m: "Gaji upah, menyuplai", s: 12, w: [["給料", "きゅうりょう", "Gaji bulanan"], ["月給", "げっきゅう", "Gaji sebulan"]] },
  { k: "月", on: "ゲツ、ガツ", kun: "つき", m: "Bulan kalender astronomi", s: 4, w: [["毎月", "まいつき", "Tiap bulan"], ["来月", "らいげつ", "Bulan depan"]] },
  { k: "火", on: "カ", kun: "ひ", m: "Api bara kobaran", s: 4, w: [["火災", "かさい", "Kebakaran fatal"], ["花火", "はなび", "Kembang api semarak"]] },
  { k: "水", on: "スイ", kun: "みず", m: "Air tawar jernih", s: 4, w: [["水道", "すいどう", "Saluran pipa air PAM"], ["水泳", "すいえい", "Berenang olahraga"]] },
  { k: "木", on: "モク、ボク", kun: "き", m: "Pohon kayu belantara", s: 4, w: [["木曜日", "もくようび", "Hari Kamis"], ["植木", "うえき", "Tanaman pot kebun"]] },
  { k: "金", on: "キン、コン", kun: "かね", m: "Emas logam, uang kas", s: 8, w: [["現金", "げんきん", "Uang tunai cash"], ["貯金", "ちょきん", "Uang tabungan"]] },
  { k: "土", on: "ド、ト", kun: "つち", m: "Tanah bumi tanah liat", s: 3, w: [["土地", "とち", "Tanah kapling lahan"], ["土曜日", "どようび", "Hari Sabtu"]] },

  // 261-280
  { k: "地", on: "チ、ジ", kun: "", m: "Bumi daratan tempat", s: 6, w: [["地震", "じしん", "Gempa bumi tektonik"], ["地域", "ちいき", "Wilayah teritorial"]] },
  { k: "震", on: "シン", kun: "ふる・える", m: "Guncangan getaran gempa", s: 15, w: [["震度", "しんど", "Skala intensitas gempa"], ["震える", "ふるえる", "Gemetar kedinginan"]] },
  { k: "域", on: "イキ", kun: "", m: "Zona teritori kawasan", s: 11, w: [["区域", "くいき", "Zona batasan wilayah"], ["流域", "りゅういき", "Daerah aliran sungai DAS"]] },
  { k: "流", on: "リュウ、ル", kun: "なが・れる、なが・す", m: "Mengalir, arus tren", s: 10, w: [["流行", "りゅうこう", "Tren populer mewabah"], ["一流", "いちりゅう", "Kelas wahid ternama"]] },
  { k: "行", on: "コウ、ギョウ", kun: "い・く、ゆ・く、おこな・う", m: "Pergi, menyelenggarakan", s: 6, w: [["行動", "こうどう", "Tindakan aksi laku"], ["行事", "ぎょうじ", "Agenda acara festival"]] },
  { k: "事", on: "ジ", kun: "こと", m: "Urusan hal fakta peristiwa", s: 8, w: [["大事", "だいじ", "Penting krusial"], ["食事", "しょくじ", "Makan bersantap"]] },
  { k: "食", on: "ショク", kun: "た・べる、く・う", m: "Makan, pangan panganan", s: 9, w: [["定食", "ていしょく", "Menu paket komplit"], ["外食", "がいしょく", "Makan di luar resto"]] },
  { k: "飲", on: "イン", kun: "の・む", m: "Minum meneguk", s: 12, w: [["飲料水", "いんりょうすい", "Air minum bersih"], ["飲み物", "のみもの", "Minuman"]] },
  { k: "物", on: "ブツ、モツ", kun: "もの", m: "Barang benda zat", s: 8, w: [["荷物", "にもつ", "Barang bawaan paket"], ["本物", "ほんもの", "Asli original bukan tiruan"]] },
  { k: "荷", on: "カ", kun: "に", m: "Beban bawaan muatan", s: 10, w: [["手荷物", "てにもつ", "Tas tenteng kabin"], ["重荷", "おもに", "Beban berat tanggungan"]] },
  { k: "重", on: "ジュウ", kun: "かさ・ねる", m: "Bertumpuk rangkap", s: 9, w: [["貴重", "きちょう", "Amat berharga bernilai"], ["重複", "ちょうふく", "Duplikasi tumpang tindih"]] },
  { k: "貴", on: "キ", kun: "とうと・い", m: "Mulia terhormat berharga", s: 12, w: [["貴重品", "きちょうひん", "Barang berharga mulia"], ["貴族", "きぞく", "Bangsawan priyayi"]] },
  { k: "族", on: "ゾク", kun: "", m: "Keluarga klan suku", s: 11, w: [["家族", "かぞく", "Keluarga inti"], ["民族", "みんぞく", "Etnis suku bangsa"]] },
  { k: "親", on: "シン", kun: "おや、した・しい", m: "Orang tua, akrab karib", s: 16, w: [["両親", "りょうしん", "Kedua orang tua"], ["親切", "しんせつ", "Baik hati ramah"]] },
  { k: "切", on: "セツ、サイ", kun: "き・る、き・れる", m: "Memotong, mendesak", s: 4, w: [["切手", "きって", "Prangko pos"], ["切符", "きっぷ", "Karcis tiket karcis"]] },
  { k: "符", on: "フ", kun: "", m: "Kupon tanda token tiket", s: 11, w: [["音符", "おんぷ", "Not balok balok nada"], ["符号", "ふごう", "Tanda simbol kode"]] },
  { k: "券", on: "ケン", kun: "", m: "Voucher tiket karcis kupon", s: 8, w: [["定期券", "ていきけん", "Tiket komuter terusan"], ["旅券", "りょけん", "Paspor buku paspor"]] },
  { k: "旅", on: "リョ", kun: "たび", m: "Bepergian bertamasya safar", s: 10, w: [["旅行", "りょこう", "Wisata melancong"], ["旅館", "りょかん", "Penginapan ryokan Jepang"]] },
  { k: "宿", on: "シュク", kun: "やど、やど・る", m: "Penginapan losmen bermalam", s: 11, w: [["宿泊", "しゅくはく", "Menginap reservasi"], ["宿題", "しゅくだい", "PR pekerjaan rumah"]] },
  { k: "泊", on: "ハク", kun: "と・まる、と・める", m: "Bermalam menginap", s: 8, w: [["一泊二日", "いっぱくふつか", "2 hari 1 malam"], ["泊まる", "とまる", "Menginap di hotel"]] },

  // 281-300
  { k: "題", on: "ダイ", kun: "", m: "Judul tema materi soal", s: 18, w: [["問題", "もんだい", "Masalah kendala soal"], ["話題", "わだい", "Topik perbincangan hangat"]] },
  { k: "話", on: "ワ", kun: "はな・す、はなし", m: "Berbicara, cerita kisah", s: 13, w: [["会話", "かいわ", "Percakapan dialog"], ["電話", "でんわ", "Telepon hubungan suara"]] },
  { k: "電", on: "デン", kun: "", m: "Listrik kilat petir", s: 13, w: [["電力", "でんりょく", "Tenaga daya listrik"], ["電子", "でんし", "Elektronik digital"]] },
  { k: "力", on: "リョク、リキ", kun: "ちから", m: "Tenaga daya kekuatan", s: 2, w: [["能力", "のうりょく", "Kapabilitas kemampuan"], ["努力", "どりょく", "Upaya ikhtiar gigih"]] },
  { k: "能", on: "ノウ", kun: "", m: "Kemampuan bakat fungsi", s: 10, w: [["可能", "かのう", "Mungkin terealisasi"], ["才能", "さいのう", "Bakat talenta seni"]] },
  { k: "努", on: "ド", kun: "つと・める", m: "Berikhtiar berusaha keras", s: 7, w: [["努力家", "どりょくか", "Orang pekerja keras"], ["努める", "つとめる", "Berupaya sekuat tenaga"]] },
  { k: "勤", on: "キン、ゴン", kun: "つと・める", m: "Dinas bekerja mengabdi", s: 12, w: [["通勤", "つうきん", "Pergi pulang kantor"], ["勤務", "きんむ", "Jam tugas kerja kantor"]] },
  { k: "務", on: "ム", kun: "つと・める", m: "Tugas kewajiban fungsi", s: 11, w: [["事務所", "じむしょ", "Kantor dinas studio"], ["公務員", "こうむいん", "PNS pegawai negeri"]] },
  { k: "公", on: "コウ", kun: "おおやけ", m: "Publik umum terbuka resmi", s: 4, w: [["公園", "こうえん", "Taman umum kota"], ["公式", "こうしき", "Resmi formal formula"]] },
  { k: "園", on: "エン", kun: "その", m: "Kebun taman asri", s: 13, w: [["動物園", "どうぶつえん", "Kebun binatang"], ["遊園地", "ゆうえんち", "Taman bermain hiburan"]] },
  { k: "遊", on: "ユウ、ユ", kun: "あそ・ぶ", m: "Bermain rekreasi riang", s: 12, w: [["遊び", "あそび", "Permainan santai"], ["周遊", "しゅうゆう", "Tur keliling darmawisata"]] },
  { k: "周", on: "シュウ", kun: "まわ・り", m: "Sekeliling putaran keliling", s: 8, w: [["周囲", "しゅうい", "Lingkungan sekitar"], ["一周年", "いっしゅうねん", "Ulang tahun genap 1 tahun"]] },
  { k: "囲", on: "イ", kun: "かこ・む、かこ・う", m: "Mengepung melingkari", s: 7, w: [["雰囲気", "ふんいき", "Atmosfer suasana hawa"], ["囲む", "かこむ", "Mengelilingi melingkari"]] },
  { k: "気", on: "キ、ケ", kun: "", m: "Hawa energi roh rasa", s: 6, w: [["気持ち", "きもち", "Perasaan hati sensasi"], ["気候", "きこう", "Iklim cuaca global"]] },
  { k: "候", on: "コウ", kun: "そうろう", m: "Musim hawa calon cuaca", s: 10, w: [["天候", "てんこう", "Kondisi cuaca harian"], ["候補", "こうほ", "Kandidat calon terpilih"]] },
  { k: "天", on: "テン", kun: "あまつ、あめ", m: "Langit surga cakrawala", s: 4, w: [["天気", "てんき", "Cuaca hari ini"], ["天才", "てんさい", "Jenius berbakat alami"]] },
  { k: "才", on: "サイ", kun: "", m: "Bakat kecerdasan umur", s: 3, w: [["秀才", "しゅうさい", "Pelajar brilian berprestasi"], ["何歳・何才", "なんさい", "Berapa umur usia"]] },
  { k: "補", on: "ホ", kun: "おぎな・う", m: "Menambal melengkapi subsidi", s: 12, w: [["補給", "ほきゅう", "Pengisian bekal pasokan"], ["補習", "ほしゅう", "Pelajaran tambahan remidi"]] },
  { k: "習", on: "シュウ", kun: "なら・う", m: "Mempelajari membiasakan", s: 11, w: [["習慣", "しゅうかん", "Kebiasaan adat tradisi"], ["練習", "れんしゅう", "Latihan drill soal"]] },
  { k: "練", on: "レン", kun: "ね・る", m: "Melatih mengasah adonan", s: 14, w: [["訓練", "くんれん", "Pelatihan simulasi gempa"], ["練る", "ねる", "Mematangkan taktik strategi"]] },

  // 301-320
  { k: "訓", on: "クン", kun: "", m: "Bimbingan didikan lafal kun", s: 10, w: [["教訓", "きょうくん", "Pelajaran moral petuah"], ["特訓", "とっくん", "Latihan kilat intensif"]] },
  { k: "慣", on: "カン", kun: "な・れる、な・らす", m: "Terbiasa akrab lazim", s: 14, w: [["慣習", "かんしゅう", "Adat istiadat kelaziman"], ["見慣れる", "みなれる", "Sudah biasa terbiasa melihat"]] },
  { k: "見", on: "ケン", kun: "み・る、み・える、み・せる", m: "Melihat tampak memperlihatkan", s: 7, w: [["意見", "いけん", "Pendapat opini pemikiran"], ["見学", "けんがく", "Kunjungan studi edukatif"]] },
  { k: "意", on: "イ", kun: "", m: "Maksud tekad makna isi batin", s: 13, w: [["意味", "いみ", "Arti makna semantik"], ["注意", "ちゅうい", "Perhatian peringatan waspada"]] },
  { k: "注", on: "チュウ", kun: "そそ・ぐ", m: "Menuang fokus perhatian order", s: 8, w: [["注文", "ちゅうもん", "Pesanan order makanan"], ["注目", "ちゅうもく", "Sorotan perhatian khalayak"]] },
  { k: "文", on: "ブン、モン", kun: "ふみ", m: "Kalimat sastra teks aksara", s: 4, w: [["文学", "ぶんがく", "Kesusastraan karya novel"], ["作文", "さくぶん", "Karangan esai tulis"]] },
  { k: "学", on: "ガク", kun: "まな・ぶ", m: "Belajar menuntut ilmu sains", s: 8, w: [["学者", "がくしゃ", "Cendekiawan sarjana peneliti"], ["留学", "りゅうがく", "Studi menuntut ilmu di LN"]] },
  { k: "留", on: "リュウ、ル", kun: "と・まる、と・める", m: "Tinggal menetap menahan", s: 10, w: [["保留", "ほりゅう", "Penangguhan pending simpan"], ["書留", "かきとめ", "Surat pos tercatat resmi"]] },
  { k: "保", on: "ホ、ホウ", kun: "たも・つ", m: "Menjaga memelihara garansi", s: 9, w: [["保護", "ほご", "Perlindungan proteksi cagar"], ["保存", "ほぞん", "Menyimpan file awet"]] },
  { k: "護", on: "ゴ", kun: "", m: "Mengawal membela membentengi", s: 20, w: [["弁護士", "べんごし", "Pengacara advokat hukum"], ["看護師", "かんごし", "Perawat suster medis"]] },
  { k: "弁", on: "ベン", kun: "", m: "Bicara dialek katup membela", s: 5, w: [["関西弁", "かんさいべん", "Dialek logat Kansai"], ["お弁当", "おべんとう", "Kotak bekal makan siang"]] },
  { k: "看", on: "カン", kun: "み・る", m: "Menjaga mengawasi merawat", s: 9, w: [["看板", "かんばん", "Papan reklame plang toko"], ["看病", "かんびょう", "Merawat orang sakit"]] },
  { k: "病", on: "ビョウ、ヘイ", kun: "や・む、やまい", m: "Sakit penyakit gangguan fisik", s: 10, w: [["病院", "びょういん", "Rumah sakit klinik"], ["病気", "びょうき", "Penyakit kondisi sakit"]] },
  { k: "院", on: "イン", kun: "", m: "Institusi balai agung lembaga", s: 10, w: [["大学院", "だいがくいん", "Sekolah pascasarjana S2/S3"], ["入院", "にゅういん", "Rawat inap di RS"]] },
  { k: "入", on: "ニュウ", kun: "はい・る、い・れる", m: "Masuk memasukkan", s: 2, w: [["入学", "にゅうがく", "Masuk sekolah tahun ajaran"], ["輸入", "ゆにゅう", "Impor komoditas masuk"]] },
  { k: "輸", on: "ユ", kun: "", m: "Mengangkut logistik lintas benua", s: 16, w: [["輸出", "ゆしゅつ", "Ekspor barang ke luar negeri"], ["輸送", "ゆそう", "Transportasi distribusi kargo"]] },
  { k: "出", on: "シュツ、スイ", kun: "で・る、だ・す", m: "Keluar mengeluarkan tampil", s: 5, w: [["出席", "しゅっせき", "Kehadiran absensi"], ["出身", "しゅっしん", "Asal kampung daerah"]] },
  { k: "身", on: "シン", kun: "み", m: "Tubuh raga status diri", s: 7, w: [["身分", "みぶん", "Identitas kedudukan status"], ["独身", "どくしん", "Lajang belum menikah"]] },
  { k: "独", on: "ドク", kun: "ひと・り", m: "Sendiri tunggal mandiri", s: 9, w: [["独立", "どくりつ", "Kemerdekaan berdikari"], ["独自", "どくじ", "Orisinil khas tersendiri"]] },
  { k: "自", on: "ジ、シ", kun: "みずか・ら", m: "Diri sendiri spontan alamiah", s: 6, w: [["自分", "じぶん", "Diri sendiri"], ["自然", "しぜん", "Alam raya naturalis"]] },

  // 321-336
  { k: "然", on: "ゼン、ネン", kun: "しか・り", m: "Demikian adanya wujud nyata", s: 12, w: [["突然", "とつぜん", "Tiba-tiba mendadak sontak"], ["当然", "とうぜん", "Sudah sepantasnya wajar"]] },
  { k: "当", on: "トウ", kun: "あ・たる、あ・てる", m: "Tepat kena sesuai tanggung", s: 6, w: [["本当", "ほんとう", "Sungguh-sungguh nyata benar"], ["担当", "たんとう", "Penanggung jawab pic tim"]] },
  { k: "担", on: "タン", kun: "にな・う、かつ・ぐ", m: "Memikul menanggung memegang", s: 8, w: [["負担", "ふたん", "Beban tanggung jawab"], ["担任", "たんにん", "Wali kelas penanggung jawab"]] },
  { k: "任", on: "ニン", kun: "まか・せる、まか・す", m: "Pasrah menugaskan menyerahkan", s: 6, w: [["責任", "せきにん", "Tanggung jawab moral tugas"], ["辞任", "じにん", "Mengundurkan diri mundur"]] },
  { k: "責", on: "セキ", kun: "せ・める", m: "Menyalahkan mendesak tugas", s: 11, w: [["非難", "ひなん", "Kecaman celaan keras"], ["責める", "せめる", "Menyalahkan menegur"]] },
  { k: "辞", on: "ジ", kun: "や・める", m: "Kamus kata mengundurkan diri", s: 13, w: [["辞書", "じしょ", "Kamus leksikon bahasa"], ["世辞", "せじ", "Pujian basa-basi sanjungan"]] },
  { k: "書", on: "ショ", kun: "か・く", m: "Menulis surat buku dokumen", s: 10, w: [["書類", "しょるい", "Berkas dokumen kertas"], ["読書", "どくしょ", "Membaca buku gemar baca"]] },
  { k: "類", on: "ルイ", kun: "たぐ・い", m: "Jenis rumpun ragam klasifikasi", s: 18, w: [["種類", "しゅるい", "Ragam macam varian"], ["人類", "じんるい", "Umat manusia sedunia"]] },
  { k: "種", on: "シュ", kun: "たね", m: "Benih biji rumpun ras", s: 14, w: [["人種", "じんしゅ", "Ras etnis suku bangsa"], ["各種", "かくしゅ", "Beraneka macam ragam"]] },
  { k: "各", on: "カク", kun: "おのおの", m: "Masing-masing tiap-tiap", s: 6, w: [["各地", "かくち", "Tiap daerah seantero negeri"], ["各国", "かっこく", "Masing-masing negara bangsa"]] },
  { k: "国", on: "コク", kun: "くに", m: "Negara tanah air bangsa", s: 8, w: [["外国", "がいこく", "Luar negeri mancanegara"], ["帰国", "きこく", "Kembali pulang ke tanah air"]] },
  { k: "帰", on: "キ", kun: "かえ・る、かえ・す", m: "Pulang kembali ke pangkuan", s: 10, w: [["日帰り", "ひがえり", "Perjalanan PP satu hari"], ["復帰", "ふっき", "Kembali beraktivitas sembuh"]] },
  { k: "復", on: "フク", kun: "また", m: "Pulih kembali lagi dobel", s: 12, w: [["回復", "かいふく", "Pemulihan kesehatan pulih"], ["復習", "ふくしゅう", "Mengulang materi pelajaran"]] },
  { k: "回", on: "カイ、エ", kun: "まわ・る、まわ・す", m: "Berputar ronde rotasi kali", s: 6, w: [["何回", "なんかい", "Berapa kali putaran"], ["回転", "かいてん", "Putaran rotasi gasing"]] },
  { k: "転", on: "テン", kun: "ころ・がる、ころ・ぶ", m: "Terguling berbelok berpindah", s: 11, w: [["自転車", "じてんしゃ", "Sepeda kayuh gowes"], ["転職", "てんしょく", "Pindah profesi karir baru"]] },
  { k: "職", on: "ショク", kun: "", m: "Pekerjaan profesi karir jawatan", s: 18, w: [["職業", "しょくぎょう", "Mata pencaharian profesi"], ["職場", "しょくば", "Tempat kerja kantor instansi"]] }
];

const kanjiList = rawKanjiData.map((item, idx) => ({
  id: `k-${idx + 1}`,
  kanji: item.k,
  on: item.on,
  kun: item.kun,
  meaning: item.m,
  strokes: item.s,
  words: item.w.map(w => ({
    word: w[0],
    reading: w[1],
    meaning: w[2]
  }))
}));

module.exports = { kanjiList };
